# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Abusech < Formula
  desc ""
  homepage ""
  version "0.0.11"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rollwagen/abusech/releases/download/0.0.11/abusech_0.0.11_darwin_arm64.tar.gz"
      sha256 "bd603636df3617f16c1bc08e0b01ce2f7d4609fe08f53bded12cdacc088dd55f"

      def install
        bin.install "abusech"
        bash_completion.install "completions/abusech.bash" => "abusech"
        zsh_completion.install "completions/abusech.zsh" => "_abusech"
        fish_completion.install "completions/abusech.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rollwagen/abusech/releases/download/0.0.11/abusech_0.0.11_darwin_amd64.tar.gz"
      sha256 "166379a1523d7cc1107c5ee49b552ea734bbecc61b304a34bc3920639b75c75a"

      def install
        bin.install "abusech"
        bash_completion.install "completions/abusech.bash" => "abusech"
        zsh_completion.install "completions/abusech.zsh" => "_abusech"
        fish_completion.install "completions/abusech.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rollwagen/abusech/releases/download/0.0.11/abusech_0.0.11_linux_arm64.tar.gz"
      sha256 "d205137308b7ed81a971ebfc6bd44abaa2e2f0f873cbf7482e1a0c429b59cf93"

      def install
        bin.install "abusech"
        bash_completion.install "completions/abusech.bash" => "abusech"
        zsh_completion.install "completions/abusech.zsh" => "_abusech"
        fish_completion.install "completions/abusech.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rollwagen/abusech/releases/download/0.0.11/abusech_0.0.11_linux_amd64.tar.gz"
      sha256 "ffe3ce1cf1f307e3120e557184251a5265cd8adb21556e877c852f794cee3b6c"

      def install
        bin.install "abusech"
        bash_completion.install "completions/abusech.bash" => "abusech"
        zsh_completion.install "completions/abusech.zsh" => "_abusech"
        fish_completion.install "completions/abusech.fish"
      end
    end
  end
end
