# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Abusech < Formula
  desc ""
  homepage ""
  version "0.0.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rollwagen/abusech/releases/download/v0.0.4/abusech_0.0.4_darwin_arm64.tar.gz"
      sha256 "3bed235e76e8cb26dbdb0515fc862a84c6c2dc21cddadfa71813d32e932b765a"

      def install
        bin.install "abusech"
        bash_completion.install "completions/abusech.bash" => "abusech"
        zsh_completion.install "completions/abusech.zsh" => "_abusech"
        fish_completion.install "completions/abusech.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rollwagen/abusech/releases/download/v0.0.4/abusech_0.0.4_darwin_amd64.tar.gz"
      sha256 "6fcc7a9edc71af1a180f4abc66e9457b36bd8e7c719f3aeb87a4c46dc38a9f20"

      def install
        bin.install "abusech"
        bash_completion.install "completions/abusech.bash" => "abusech"
        zsh_completion.install "completions/abusech.zsh" => "_abusech"
        fish_completion.install "completions/abusech.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rollwagen/abusech/releases/download/v0.0.4/abusech_0.0.4_linux_arm64.tar.gz"
      sha256 "fcac09ef30c670c78cc46d141b753b4d331df2bdf95263ce73cfe5c871bd64c7"

      def install
        bin.install "abusech"
        bash_completion.install "completions/abusech.bash" => "abusech"
        zsh_completion.install "completions/abusech.zsh" => "_abusech"
        fish_completion.install "completions/abusech.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rollwagen/abusech/releases/download/v0.0.4/abusech_0.0.4_linux_amd64.tar.gz"
      sha256 "ff18e44af3eada86d0df3b8cc758bfb7e3535b5c8fdc6c8a32e4eb1e6913833e"

      def install
        bin.install "abusech"
        bash_completion.install "completions/abusech.bash" => "abusech"
        zsh_completion.install "completions/abusech.zsh" => "_abusech"
        fish_completion.install "completions/abusech.fish"
      end
    end
  end
end
