# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Abusech < Formula
  desc ""
  homepage ""
  version "0.0.15"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/rollwagen/abusech/releases/download/v0.0.15/abusech_0.0.15_darwin_amd64.tar.gz"
      sha256 "83809aabe83b9c71351575bb688182722e1a069dade35b1a75bc2db0bf0aace3"

      def install
        bin.install "abusech"
        bash_completion.install "completions/abusech.bash" => "abusech"
        zsh_completion.install "completions/abusech.zsh" => "_abusech"
        fish_completion.install "completions/abusech.fish"
      end
    end
    on_arm do
      url "https://github.com/rollwagen/abusech/releases/download/v0.0.15/abusech_0.0.15_darwin_arm64.tar.gz"
      sha256 "899922efae21ec8d08f022e16508fc02daa9566ac03b8c539b704e5ad8c1f3a0"

      def install
        bin.install "abusech"
        bash_completion.install "completions/abusech.bash" => "abusech"
        zsh_completion.install "completions/abusech.zsh" => "_abusech"
        fish_completion.install "completions/abusech.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rollwagen/abusech/releases/download/v0.0.15/abusech_0.0.15_linux_amd64.tar.gz"
        sha256 "e0ae51102261a47f77178f9298cc2df734c36899c90fe196eb81bf11e964b53b"

        def install
          bin.install "abusech"
          bash_completion.install "completions/abusech.bash" => "abusech"
          zsh_completion.install "completions/abusech.zsh" => "_abusech"
          fish_completion.install "completions/abusech.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rollwagen/abusech/releases/download/v0.0.15/abusech_0.0.15_linux_arm64.tar.gz"
        sha256 "56e889170f0eb2cb711bb0c9231977146b77a92ae2eae90670c8c0f898c396a9"

        def install
          bin.install "abusech"
          bash_completion.install "completions/abusech.bash" => "abusech"
          zsh_completion.install "completions/abusech.zsh" => "_abusech"
          fish_completion.install "completions/abusech.fish"
        end
      end
    end
  end
end
