# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Apoch < Formula
  desc ""
  homepage ""
  version "0.0.10"
  license "Apache-2.0"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rollwagen/apoch/releases/download/0.0.10/apoch_0.0.10_darwin_arm64.tar.gz"
      sha256 "72aa664f58a97171427b55102fd312b0e876bc57cc549eb801cc1792d34a5662"

      def install
        bin.install "apoch"
        bash_completion.install "completions/apoch.bash" => "apoch"
        zsh_completion.install "completions/apoch.zsh" => "_apoch"
        fish_completion.install "completions/apoch.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rollwagen/apoch/releases/download/0.0.10/apoch_0.0.10_darwin_amd64.tar.gz"
      sha256 "100903235e987d053ec5daec83a13bd9c3465095a91c0431b632ea21ab665554"

      def install
        bin.install "apoch"
        bash_completion.install "completions/apoch.bash" => "apoch"
        zsh_completion.install "completions/apoch.zsh" => "_apoch"
        fish_completion.install "completions/apoch.fish"
      end
    end
  end
end
