# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsServices < Formula
  desc ""
  homepage ""
  version "0.0.27"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rollwagen/aws-services/releases/download/v0.0.27/aws-services_0.0.27_darwin_amd64.tar.gz"
      sha256 "f007c5a1409affb2a72fb24aad811c4847c4531388f0baa9db12f457818bfe52"

      def install
        bin.install "aws-services"
        bash_completion.install "completions/aws-services.bash" => "aws-services"
        zsh_completion.install "completions/aws-services.zsh" => "_aws-services"
        fish_completion.install "completions/aws-services.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rollwagen/aws-services/releases/download/v0.0.27/aws-services_0.0.27_darwin_arm64.tar.gz"
      sha256 "dbbe12678788a304e7a3f51a1b9ae9d67ddba9a188b4a036d783852edd49bd6b"

      def install
        bin.install "aws-services"
        bash_completion.install "completions/aws-services.bash" => "aws-services"
        zsh_completion.install "completions/aws-services.zsh" => "_aws-services"
        fish_completion.install "completions/aws-services.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rollwagen/aws-services/releases/download/v0.0.27/aws-services_0.0.27_linux_amd64.tar.gz"
      sha256 "05240bef4c425d60aed1c3caa393577df1ae28fc48387be907a1de975cfbb07a"
      def install
        bin.install "aws-services"
        bash_completion.install "completions/aws-services.bash" => "aws-services"
        zsh_completion.install "completions/aws-services.zsh" => "_aws-services"
        fish_completion.install "completions/aws-services.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rollwagen/aws-services/releases/download/v0.0.27/aws-services_0.0.27_linux_arm64.tar.gz"
      sha256 "85a3d90b00b610641c6cbd02e03fb3d5348b326a3252bfe4a709aac808ef1bf4"
      def install
        bin.install "aws-services"
        bash_completion.install "completions/aws-services.bash" => "aws-services"
        zsh_completion.install "completions/aws-services.zsh" => "_aws-services"
        fish_completion.install "completions/aws-services.fish"
      end
    end
  end
end
