# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsServices < Formula
  desc ""
  homepage ""
  version "0.0.21"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rollwagen/aws-services/releases/download/v0.0.21/aws-services_0.0.21_darwin_amd64.tar.gz"
      sha256 "1a46af0aab2607ea0e9229a8d50f3da6f38bd056ee7303a86ae13a359ba51c35"

      def install
        bin.install "aws-services"
        bash_completion.install "completions/aws-services.bash" => "aws-services"
        zsh_completion.install "completions/aws-services.zsh" => "_aws-services"
        fish_completion.install "completions/aws-services.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rollwagen/aws-services/releases/download/v0.0.21/aws-services_0.0.21_darwin_arm64.tar.gz"
      sha256 "89c85f2306673a4ee39b5b333a8382ce6d0f0c87c0a69d0a4d1df5c42226aad2"

      def install
        bin.install "aws-services"
        bash_completion.install "completions/aws-services.bash" => "aws-services"
        zsh_completion.install "completions/aws-services.zsh" => "_aws-services"
        fish_completion.install "completions/aws-services.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rollwagen/aws-services/releases/download/v0.0.21/aws-services_0.0.21_linux_arm64.tar.gz"
      sha256 "94986f4247be82c9a5eab33f7e644e9197c52bdfbc98d97d51d9e31dc2ed5406"

      def install
        bin.install "aws-services"
        bash_completion.install "completions/aws-services.bash" => "aws-services"
        zsh_completion.install "completions/aws-services.zsh" => "_aws-services"
        fish_completion.install "completions/aws-services.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rollwagen/aws-services/releases/download/v0.0.21/aws-services_0.0.21_linux_amd64.tar.gz"
      sha256 "7e164fb55ac2068848e382bdbd97c617aab0e2d3c3dbb81a617e4c763d12b1bc"

      def install
        bin.install "aws-services"
        bash_completion.install "completions/aws-services.bash" => "aws-services"
        zsh_completion.install "completions/aws-services.zsh" => "_aws-services"
        fish_completion.install "completions/aws-services.fish"
      end
    end
  end
end
