# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsServices < Formula
  desc ""
  homepage ""
  version "0.0.15"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rollwagen/aws-services/releases/download/v0.0.15/aws-services_0.0.15_darwin_arm64.tar.gz"
      sha256 "7a2387350fd06218ab8b6471a7f823d7e3cc460213288f9be46e550ad5dcc414"

      def install
        bin.install "aws-services"
        bash_completion.install "completions/aws-services.bash" => "aws-services"
        zsh_completion.install "completions/aws-services.zsh" => "_aws-services"
        fish_completion.install "completions/aws-services.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rollwagen/aws-services/releases/download/v0.0.15/aws-services_0.0.15_darwin_amd64.tar.gz"
      sha256 "b6c68e99a64d7d60d2e2f92ca993e957bcbda6f2745bcaa8419a381e8f2e7ac9"

      def install
        bin.install "aws-services"
        bash_completion.install "completions/aws-services.bash" => "aws-services"
        zsh_completion.install "completions/aws-services.zsh" => "_aws-services"
        fish_completion.install "completions/aws-services.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rollwagen/aws-services/releases/download/v0.0.15/aws-services_0.0.15_linux_amd64.tar.gz"
      sha256 "f53a715a614fd5a7cf69ba84e052bf245a9cefd0aee5b7d2fce51eff648e3b26"

      def install
        bin.install "aws-services"
        bash_completion.install "completions/aws-services.bash" => "aws-services"
        zsh_completion.install "completions/aws-services.zsh" => "_aws-services"
        fish_completion.install "completions/aws-services.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rollwagen/aws-services/releases/download/v0.0.15/aws-services_0.0.15_linux_arm64.tar.gz"
      sha256 "8d1a21976a0d9d5a98bdb472769628b8782994bfe8112af77a5e8fb7e1ffdd7b"

      def install
        bin.install "aws-services"
        bash_completion.install "completions/aws-services.bash" => "aws-services"
        zsh_completion.install "completions/aws-services.zsh" => "_aws-services"
        fish_completion.install "completions/aws-services.fish"
      end
    end
  end
end
