# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bods < Formula
  desc ""
  homepage ""
  version "0.0.28"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/rollwagen/bods/releases/download/0.0.28/bods_0.0.28_darwin_amd64.tar.gz"
    sha256 "8d84af9d04fc8f65f170f9a0f05e7264f80d8cd54c9a15c89ddf99d95401dd44"

    define_method(:install) do
      bin.install "bods"
      bash_completion.install "completions/bods.bash" => "bods"
      zsh_completion.install "completions/bods.zsh" => "_bods"
      fish_completion.install "completions/bods.fish"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/rollwagen/bods/releases/download/0.0.28/bods_0.0.28_darwin_arm64.tar.gz"
    sha256 "da37ae5bc1bb40c3487d2736dc411b37afeb99d2e33332f014c80407b6620d5f"

    define_method(:install) do
      bin.install "bods"
      bash_completion.install "completions/bods.bash" => "bods"
      zsh_completion.install "completions/bods.zsh" => "_bods"
      fish_completion.install "completions/bods.fish"
    end
  end
end
