# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bods < Formula
  desc ""
  homepage ""
  version "0.0.21"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/rollwagen/bods/releases/download/0.0.21/bods_0.0.21_darwin_amd64.tar.gz"
    sha256 "d3d31317865664407383c7e8cfcc8ce48d15e2bb7348e3c868ea1b0404f7bbb1"

    def install
      bin.install "bods"
      bash_completion.install "completions/bods.bash" => "bods"
      zsh_completion.install "completions/bods.zsh" => "_bods"
      fish_completion.install "completions/bods.fish"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/rollwagen/bods/releases/download/0.0.21/bods_0.0.21_darwin_arm64.tar.gz"
    sha256 "bcc9dea6fc9bbd9c777d8edf82f7afc06063ed283a04b9828cd1f54e9abd35a4"

    def install
      bin.install "bods"
      bash_completion.install "completions/bods.bash" => "bods"
      zsh_completion.install "completions/bods.zsh" => "_bods"
      fish_completion.install "completions/bods.fish"
    end
  end
end
