# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bods < Formula
  desc ""
  homepage ""
  version "0.0.9"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/rollwagen/bods/releases/download/0.0.9/bods_0.0.9_darwin_amd64.tar.gz"
    sha256 "ccca2b875f99bf8c98fca8173ffdfc68b6a0a3f2de397451659f4d08b91b00d3"

    def install
      bin.install "bods"
      bash_completion.install "completions/bods.bash" => "bods"
      zsh_completion.install "completions/bods.zsh" => "_bods"
      fish_completion.install "completions/bods.fish"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/rollwagen/bods/releases/download/0.0.9/bods_0.0.9_darwin_arm64.tar.gz"
    sha256 "498995091a3b586e2c0d12949b9ca36a1c3acc274b8c010e356ca12bdf0fc661"

    def install
      bin.install "bods"
      bash_completion.install "completions/bods.bash" => "bods"
      zsh_completion.install "completions/bods.zsh" => "_bods"
      fish_completion.install "completions/bods.fish"
    end
  end
end
