# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clown < Formula
  desc ""
  homepage ""
  version "0.0.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rollwagen/clown/releases/download/v0.0.3/clown_0.0.3_darwin_arm64.tar.gz"
      sha256 "7c6910d4d5c5064676ca7a78c4c1fe8b5707f5e5950b0ce6dee72f3f74bb3908"

      def install
        bin.install "clown"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rollwagen/clown/releases/download/v0.0.3/clown_0.0.3_darwin_amd64.tar.gz"
      sha256 "a4bb56962626feeac04ba4ab29ca6da3f595a803b46b4229c1cefd2b55ecba8f"

      def install
        bin.install "clown"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rollwagen/clown/releases/download/v0.0.3/clown_0.0.3_linux_arm64.tar.gz"
      sha256 "c202e890f8a2f8f55ce7f626ffdbd483657618aaae1c8cdcde166ec16af89182"

      def install
        bin.install "clown"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rollwagen/clown/releases/download/v0.0.3/clown_0.0.3_linux_amd64.tar.gz"
      sha256 "533b09dae15a5ca2a2b8245fe9fc3b5cbb0224c42c2367cf13604ccfc2ab1035"

      def install
        bin.install "clown"
      end
    end
  end
end
