# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clown < Formula
  desc ""
  homepage ""
  version "0.0.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rollwagen/clown/releases/download/v0.0.4/clown_0.0.4_darwin_arm64.tar.gz"
      sha256 "28ac40389e259b8641f47c485e017bc0b18a6f254aed73ad51a27a8cb8df7277"

      def install
        bin.install "clown"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rollwagen/clown/releases/download/v0.0.4/clown_0.0.4_darwin_amd64.tar.gz"
      sha256 "037b92d35cbd63542434d82c4ec07687c628841263634ede1772e8e81d041a53"

      def install
        bin.install "clown"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rollwagen/clown/releases/download/v0.0.4/clown_0.0.4_linux_amd64.tar.gz"
      sha256 "2ab5d750bd9517c4b330787075f44a819ee99586017736b70003c53c7ac29149"

      def install
        bin.install "clown"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rollwagen/clown/releases/download/v0.0.4/clown_0.0.4_linux_arm64.tar.gz"
      sha256 "37b95e7a453504d4f35a4075fc394c210b4466e657da48764f78f59a79f07571"

      def install
        bin.install "clown"
      end
    end
  end
end
