# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clown < Formula
  desc ""
  homepage ""
  version "0.0.19"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rollwagen/clown/releases/download/0.0.19/clown_0.0.19_darwin_arm64.tar.gz"
      sha256 "4dcf626b85b8bad1fdc7c89f2673b9d36d39bf47fafe941a89ded307ad0d7d18"

      def install
        bin.install "clown"
        bash_completion.install "completions/clown.bash" => "clown"
        zsh_completion.install "completions/clown.zsh" => "_clown"
        fish_completion.install "completions/clown.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rollwagen/clown/releases/download/0.0.19/clown_0.0.19_darwin_amd64.tar.gz"
      sha256 "4bfd39ee27196a6ba4ccf4985ebfad925e5a1c58a2ac621b7b54f78ea70c9b2c"

      def install
        bin.install "clown"
        bash_completion.install "completions/clown.bash" => "clown"
        zsh_completion.install "completions/clown.zsh" => "_clown"
        fish_completion.install "completions/clown.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rollwagen/clown/releases/download/0.0.19/clown_0.0.19_linux_arm64.tar.gz"
      sha256 "dcba0b1fd2da96af3b7095f273cb74f381eb08357a6edc3c6e9c76583c8a5349"

      def install
        bin.install "clown"
        bash_completion.install "completions/clown.bash" => "clown"
        zsh_completion.install "completions/clown.zsh" => "_clown"
        fish_completion.install "completions/clown.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rollwagen/clown/releases/download/0.0.19/clown_0.0.19_linux_amd64.tar.gz"
      sha256 "a4fd45e60adc11294bac8ff31f8059075c3d9d94ff7abffd7899a76a40417741"

      def install
        bin.install "clown"
        bash_completion.install "completions/clown.bash" => "clown"
        zsh_completion.install "completions/clown.zsh" => "_clown"
        fish_completion.install "completions/clown.fish"
      end
    end
  end
end
