# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ilconte < Formula
  desc ""
  homepage ""
  version "0.0.4"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/rollwagen/ilconte/releases/download/0.0.4/ilconte_0.0.4_darwin_amd64.tar.gz"
    sha256 "5f9ff88ef3f27437bc77f276babd357466113f253ea17a3078f8f3cf67dadcc2"

    def install
      bin.install "conte"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/rollwagen/ilconte/releases/download/0.0.4/ilconte_0.0.4_darwin_arm64.tar.gz"
    sha256 "68ce7e42fbeb076857f2a840912b4548d2713df9096ec57f3c9dc921a4770717"

    def install
      bin.install "conte"
    end
  end
end
