# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ilconte < Formula
  desc ""
  homepage ""
  version "0.0.5"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/rollwagen/ilconte/releases/download/0.0.5/ilconte_0.0.5_darwin_amd64.tar.gz"
    sha256 "f4b6668e2e9a86e8bd2537e520b07a203816031d13b2daaacdbf29d27c49c61d"

    def install
      bin.install "conte"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/rollwagen/ilconte/releases/download/0.0.5/ilconte_0.0.5_darwin_arm64.tar.gz"
    sha256 "f22a62b91ffd076602c74decc24c93604e8421fc4195ef9391982be1e0185cbc"

    def install
      bin.install "conte"
    end
  end
end
